experiment:
  gpu: 0
  backend: pytorch
  models:
    external.BPRMF:
      meta:
        save_weights: True
        save_recs: True
      lr: [ 1.e-3 ]
      batch_size: [ 256 ]
      factors: [ 128 ]
      l_w: [  1.e-3 ]
      # I experience that 200 is too few on onion
      epochs: 500