experiment:
  models:
    BPRMF:
          <<: *model_defaults
          lr: [0.0005, 0.001, 0.005, 0.01]
          batch_size: [128, 256, 512]
          epochs: 50
          bias_regularization: 0
          user_regularization: [0.0025, 0.005, 0.01]
          positive_item_regularization: [0.0025, 0.005, 0.01]
          negative_item_regularization: [0.00025, 0.0005, 0.001]
          update_negative_item_factors: True
          update_users: True
          update_items: True
          update_bias: True