experiment:
  gpu: 2
  backend: pytorch
  models:
    external.CoBraR:
      meta:
        save_weights: False
        save_recs: False
      #
      lr: [ 1.e-6, 1.e-7 ] # Way better than 1.e-3 and 1.e-2
      # not really relevant
      batch_size: [ 256 ]
      dropout: [ 0.9 ]
      batch_norm: [True, False]
      # not really relevant
      reg: [ 1.e-2, 1.e-3 ] # 1.e-1 already ran
      # already 128 gives OOM on rk4 with batch size 256 and no intermediate layers
      # 64 still to try
      embedding_dim: [ 64, 128 ] # [ 256, 128, 64 ]: results were all over the place
      #
      user_mlp: [ [] ]
      #
      item_mlp: [ [] ] # [ [ 1024, 512 ], [] ] # [ [1024, 512, 256], [1024, 512], [512, 256] ]
      #
      #
      collaborative_branch: [ [ 2048 ], [ 1024 ], [ 512 ], [ 256 ]] # [ [1024, 512, 256], [1024, 512], [512, 256] ]
      neg_ratio: [ 5 ] # 1 , 10, 20, 100 ]
      similarity: cosine

      early_stopping:
        verbose: False
        patience: 10
        monitor: nDCG@5