experiment:
  backend: pytorch
  gpu: 0
  models:
    external.DeepMF:
      meta:
        save_weights: False
        save_recs: False
      #
      lr: [ 1.e-6, 1.e-7 ]
      # not really relevant
      batch_size: [ 256 ]
      # not really relevant
      reg: [ 1.e-2, 1.e-3 ]
      embedding_dim: [ 64, 128 ] #
      # should be the same for user and item, selected in [ [ 2048 ], [ 1024 ], [ 512 ], [ 256 ]]
      # already tried: 256, 512
      user_mlp: [ [2048] ]
      #
      item_mlp: [ [2048] ]
      neg_ratio: [ 5 ] # 1 , 10, 20, 100 ]
      similarity: cosine

      early_stopping:
        verbose: False
        patience: 10
        monitor: nDCG@5