experiment:
  backend: pytorch
  models:
    external.DeepMF:
      #
      lr: [ 1.e-4 ]
      #
      reg: [ 1.e-3 ]
      #
      embedding_dim: [ 64 ] # [ 256, 128 ]
      #
      user_mlp: [ [] ] # [ [ 512, 256 ], [256], [] ]
      #
      item_mlp: [ [] ] # [ [ 1024, 512 ], [] ] # [ [1024, 512, 256], [1024, 512], [512, 256] ]
      #
      neg_ratio: 5 # [ 5, 10, 20 ]
      similarity: cosine