experiment:
  gpu: 1
  models:
    MultiVAE:
      meta:
        save_weights: False
        save_recs: False
      lr: [ 1.e-5,  1.e-4,  1.e-3,  1.e-2 ]
      batch_size: [ 128 ]
      factors: [ 256, 128, 64 ]
      intermediate_dim: [ 1024, 512, 256 ]
      dropout_pkeep: [ 0.1, 1., 0.5 ]
      reg_lambda: [ 0.0, 0.1, 10. ]
      # I experience that 200 is too few on onion
      epochs: 500