experiment:
  backend: pytorch
  models:
    external.SiBraR:
      lr: [ 1e-5, 1e-6 ]
      num_neg: [ 10 ]
      norm_input_feat: [ False ]
      input_dim: [ 1024 ]
      norm_sbra_input: [ False ]
      mid_layers: [ [512, 256], [128], [] ]
      emb_dim: [  128, 64 ]
      # When to apply batch normalization
      # This is batch_norm_every in SiBraR
      # 0 ... deactivate, 1+ ... every n layers, -1 ... only last layer
      # WIP still not working
#      b_norm_e: -1
      w_decay: [  1e-2, 1e-3 ]
      dropout: [ 1e-1, 1e-2 ]
      # use_user_profile i.e., users interactions for embedding users
      u_prof: True
      cl_weight: [ 1.e-6 ]
      cl_temp: [ 1.e-1 ]