experiment:
  backend: pytorch
  models:
    external.SiBraR:
      # to optimize
      lr: [ 1.e-4, 1.e-3, 1.e-2 ] # [ 1e-6, 1e-5, 1e-4 ]
      num_neg: [ 10 ]
      norm_input_feat: [ False ]
      input_dim: [ 1024, 512 ]
      norm_sbra_input: [ False ]
      mid_layers: [ [512, 512, 256], [512, 512, 256, 256] ] #, [512, 256], [128], [] ]
      # To optimize
      emb_dim: [  256, 128, 64 ]
      # When to apply batch normalization
      # This is batch_norm_every in SiBraR
      # 0 ... deactivate, 1+ ... every n layers, -1 ... only last layer
      # WIP still not working
#      b_norm_e: -1
      w_decay: [  1.e-2 ] #, 1.e-3 ]
      dropout: [ 1.e-1 ] # , 1.e-2 ]
      # use_user_profile i.e., users interactions for embedding users
      u_prof: True
      cl_weight: [ 1.e-6 ]
      cl_temp: [ 1.e-1 ]