experiment:
  gpu: 0
  backend: pytorch
  models:
    external.SiBraR:
      meta:
        save_weights: False
        save_recs: False
      # to optimize
      lr: [ 1e-6 ]
      num_neg: [ 5 ]
      # Setting to true makes everything very bumpy
      norm_input_feat: [ False ]
      input_dim: [ 512 ]
      # Setting to true decreases performance
      norm_sbra_input: [ False ]
      mid_layers: [ [512, 512] ]# [512, 512, 256, 256, 128, 128, 64, 64] ]
      # To optimize
      emb_dim: [ 64 ]
      # When to apply batch normalization
      # This is batch_norm_every in SiBraR
      # 0 ... deactivate, 1+ ... every n layers, -1 ... only last layer
      # WIP still not working
      b_norm: True
      w_decay: [  1.e-2 ]
      dropout: [ 5.e-1 ]
      # use_user_profile i.e., users interactions for embedding users
      u_prof: [ False ] # False, True ]
      cl_weight: [ 1.e-1 ]
      cl_temp: [ 1. ]

      modalities: "('textual',)"
      loaders: "('TextualAttribute',)"

      early_stopping:
        verbose: False
        patience: 5
        monitor: nDCG@5