experiment:
  gpu: 0
  backend: pytorch
  models:
    external.SiBraR:
      meta:
        save_weights: False
        save_recs: False
      # to optimize
      lr: [ 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9 ] # [ 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9 ]
      num_neg: [ 5 ]
      # Setting to true makes everything very bumpy
      norm_input_feat: [ False ]
      input_dim: [ 512 ]
      # Setting to true decreases performance
      norm_sbra_input: [ False ]
      mid_layers: [ [256] ]
      # To optimize
      emb_dim: [ 128 ]
      b_norm: True
      w_decay: [  1.e-1 ]
      dropout: [ 5.e-1 ]
      # use_user_profile i.e., users interactions for embedding users
      u_prof: [ True ] # False, True ]
      cl_weight: [ 1.e-7 ]
      cl_temp: [ 1. ]

      early_stopping:
        verbose: False
        patience: 5
        monitor: nDCG@5