experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
  dataset: onion
  top_k: 20
  evaluation:
    cutoffs: [ 20 ]
    simple_metrics: [ nDCG ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.CoBraR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: nDCG@20
        restore: False
      epochs: 50
      batch_size: 128
      # "optimized"
      lr: [ 1.e-4 ]
      # "optimized"
      reg: [ 1.e-3 ]
      # "optimized"
      embedding_dim: [ 64 ] # 128, 256, 64 ]
      # "optimized"
      user_mlp: [ [] ] # [ [ 512, 256 ], [256], [] ]
      # "optimized"
      item_mlp: [ [1024], [512] ] #  [ [2048, 1024] ] seems to be problematic
      # "optimized"
      collaborative_branch: [ [1024, 512, 512, 256, 256, 128 ] ] # [ [1024, 512, 256], [1024, 512], [512, 256], [256], [128] ]
      neg_ratio: 5 # [ 5, 10, 20 ]
      similarity: cosine
      early_stopping:
        patience: 5
        mode: auto
        monitor: nDCG@20
        verbose: True