experiment:
  backend: pytorch
  data_config:
    strategy: dataset
    dataset_path: ../dataset/{0}/interactions.tsv
    side_information:
      # - dataloader: VisualAttribute
      #   visual_features: ../dataset/{0}/visual_embeddings/resnet
      # - dataloader: TextualAttribute
      #   textual_features: ../dataset/{0}/textual_embeddings/bert
      # - dataloader: AudioAttribute
      #   audio_features: ../dataset/{0}/audio_embeddings/musicnn
      - dataloader: EmotionCategoricalAttributes
        emotion_categorical_features: ../dataset/{0}/emotion_embeddings/gems
      - dataloader: EmotionAttribute
        emotion_features: ../dataset/{0}/emotion_embeddings/gems
  prefiltering:
    strategy: iterative_k_core
    core: 5
  splitting:
    #save_on_disk: True
    #save_folder: ../dataset/{0}/splits
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
    validation_splitting:
      strategy: random_subsampling
      test_ratio: 0.1
  top_k: 20
  evaluation:
    cutoffs: [ 1, 5, 10, 20]
    simple_metrics: [ Recall, Precision, nDCG, HR, EFD, EPC, ARP, PopREO, PopRSP ]
    paired_ttest: False
    wilcoxon_test: False
  gpu: 0
  external_models_path: ../external/models/__init__.py