experiment:
  dataset: emma-sample
  models:
    AttributeItemKNN:
      meta:
        save_recs: False
      loader: EmotionCategoricalAttributes
      neighbors: 40
      similarity: cosine
    FM:
      meta:
        save_recs: True
      loader: EmotionCategoricalAttributes
      epochs: 10
      batch_size: 512
      factors: 10
      lr: 0.001
      reg: 0.1