model_defaults: &model_defaults
  meta:
    hyper_opt_alg: grid
    verbose: False
    save_weights: False
    save_recs: False
    validation_rate: 1
    validation_metric: nDCG@10
    restore: False
  epochs: 200
  batch_size: 512
  #factors: 64
  loader: EmotionCategoricalAttributes
  seed: 123
  early_stopping:
    verbose: False
    patience: 5
    monitor: nDCG@10
experiment:
  dataset: emma_sample
  models:
    AttributeItemKNN:
      <<: *model_defaults
      neighbors: [ 50, 70, 100 ]
      similarity: [ cosine, euclidean ]
      implementation: standard
    FM:
      <<: *model_defaults
      factors: [10, 20]
      lr: 0.001
      reg: 0.1