model_defaults: &model_defaults
  meta:
    hyper_opt_alg: grid
    verbose: False
    save_weights: False
    save_recs: False
    validation_rate: 1
    validation_metric: nDCG@10
    restore: False
  epochs: 200
  batch_size: 512
  factors: 64
  modalities: ('emotion', )
  loaders: ('EmotionAttribute', )
  seed: 123
  early_stopping:
    verbose: False
    patience: 5
    monitor: nDCG@10
experiment:
  dataset: emma
  models:
    Random:
      <<: *model_defaults
    MostPop:
      <<: *model_defaults
    ItemKNN:
      <<: *model_defaults
      neighbors: [50, 70, 100]
      similarity: [cosine, euclidean]
      implementation: standard
    NeuMF:
      <<: *model_defaults
      lr: [0.0005, 0.001, 0.005, 0.01]
      batch_size: [128, 256, 512]
      epochs: 50
      mf_factors: [8, 16, 32]
      mlp_factors: [8, 16]
      mlp_hidden_size: [(32, 16, 8), (64, 32, 16)]
      prob_keep_dropout: 0.2
      is_mf_train: True
      is_mlp_train: True