experiment:
  backend: pytorch
  data_config:
    dataset_path: ../dataset/{0}/interactions.tsv
    side_information:
    - dataloader: EmotionAttribute
      emotion_features: ../dataset/{0}/emotion_embeddings/gems
    strategy: dataset
  dataset: emma
  evaluation:
    cutoffs:
    - 1
    - 5
    - 10
    - 20
    paired_ttest: false
    simple_metrics:
    - Recall
    - Precision
    - nDCG
    - HR
    - EFD
    - EPC
    - ARP
    - PopREO
    - PopRSP
    wilcoxon_test: false
  external_models_path: ../external/models/__init__.py
  gpu: 0
  models:
    BPRMF:
      batch_size:
      - 128
      - 256
      - 512
      bias_regularization: 0
      early_stopping: &id001
        monitor: nDCG@10
        patience: 5
        verbose: false
      epochs: 50
      factors: 64
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
      meta: &id002
        hyper_opt_alg: grid
        restore: false
        save_recs: false
        save_weights: false
        validation_metric: nDCG@10
        validation_rate: 1
        verbose: false
      modalities: ('emotion', )
      negative_item_regularization:
      - 0.00025
      - 0.0005
      - 0.001
      positive_item_regularization:
      - 0.0025
      - 0.005
      - 0.01
      seed: 123
      update_bias: true
      update_items: true
      update_negative_item_factors: true
      update_users: true
      user_regularization:
      - 0.0025
      - 0.005
      - 0.01
    ItemKNN:
      early_stopping: *id001
      epochs: 200
      factors: 64
      implementation: standard
      loaders: ('EmotionAttribute', )
      meta: *id002
      modalities: ('emotion', )
      neighbors:
      - 50
      - 70
      - 100
      seed: 123
      similarity:
      - cosine
      - euclidean
    NeuMF:
      batch_size:
      - 128
      - 256
      - 512
      early_stopping: *id001
      epochs: 50
      factors: 64
      is_mf_train: true
      is_mlp_train: true
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
      meta: *id002
      mf_factors:
      - 8
      - 16
      - 32
      mlp_factors:
      - 8
      - 16
      mlp_hidden_size:
      - (32
      - 16
      - 8)
      - (64
      - 32
      - 16)
      modalities: ('emotion', )
      prob_keep_dropout: 0.2
      seed: 123
    Random:
      early_stopping: *id001
      epochs: 200
      factors: 64
      loaders: ('EmotionAttribute', )
      meta: *id002
      modalities: ('emotion', )
      seed: 123
    external.BM3:
      batch_size: 1024
      cl_weight: 2.0
      dropout: 0.3
      early_stopping: *id001
      epochs: 200
      factors: 64
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0001
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
      lr_sched: (1.0,50)
      meta: *id002
      modalities: ('emotion', )
      multimod_factors: 64
      n_layers: 2
      reg_weight:
      - 0.1
      - 0.01
      seed: 123
    external.CLCRec:
      batch_size:
      - 512
      - 1024
      early_stopping: *id001
      epochs: 200
      factors: 64
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0001
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
      lr_lambda:
      - 0.1
      - 0.5
      - 0.9
      meta: *id002
      modalities: ('emotion', )
      num_neg:
      - 32
      - 64
      - 128
      num_sample: 0.5
      reg_weight:
      - 0.1
      - 0.01
      - 0.001
      seed: 123
      temperature:
      - 0.1
      - 0.5
      - 1.0
      - 2.0
    external.FREEDOM:
      batch_size: 1024
      drop: 0.8
      early_stopping: *id001
      epochs: 200
      factors: 64
      factors_multimod: 64
      l_w:
      - 1e-5
      - 1e-2
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0001
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
      lr_sched: (1.0,50)
      meta: *id002
      modalities: ('emotion', )
      mw: (0.1,0.9)
      n_layers: 1
      n_ui_layers: 2
      seed: 123
      top_k: 10
    external.GRCN:
      aggregation: add
      batch_size: 1024
      early_stopping: *id001
      epochs: 200
      factors: 64
      factors_multimod: 128
      fusion_mode: concat
      has_act: false
      l_w:
      - 1e-5
      - 1e-2
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      meta: *id002
      modalities: ('emotion', )
      num_layers: 2
      num_routings: 3
      pruning: true
      seed: 123
      weight_mode: confid
    external.LATTICE:
      batch_size: 1024
      early_stopping: *id001
      epochs: 200
      factors: 64
      factors_multimod: 64
      l_m: 0.7
      l_w:
      - 1e-5
      - 1e-2
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0001
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
      meta: *id002
      modalities: ('emotion', )
      n_layers: 1
      n_ui_layers: 2
      seed: 123
      top_k: 20
    external.MMGCN:
      aggregation: mean
      batch_size: 1024
      concatenation: false
      early_stopping: *id001
      epochs: 200
      factors: 64
      factors_multimod: (256, None)
      has_id: true
      l_w:
      - 1e-5
      - 1e-2
      loaders: ('EmotionAttribute', )
      lr:
      - 1.0e-05
      - 3.0e-05
      - 0.0001
      - 0.001
      - 0.01
      meta: *id002
      modalities: ('emotion', )
      num_layers: 3
      seed: 123
    external.MostPop:
      early_stopping: *id001
      epochs: 200
      factors: 64
      loaders: ('EmotionAttribute', )
      meta: *id002
      modalities: ('emotion', )
      seed: 123
    external.VBPR:
      batch_size:
      - 512
      - 1024
      comb_mod: concat
      early_stopping: *id001
      epochs: 200
      factors: 64
      l_w:
      - 1e-5
      - 1e-2
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0001
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
      meta: *id002
      modalities: ('emotion', )
      seed: 123
  prefiltering:
    core: 5
    strategy: iterative_k_core
  splitting:
    save_folder: ../data/{0}/splits
    save_on_disk: true
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
    validation_splitting:
      strategy: random_subsampling
      test_ratio: 0.1
  top_k: 20
model_defaults:
  early_stopping: *id001
  epochs: 200
  factors: 64
  loaders: ('EmotionAttribute', )
  meta: *id002
  modalities: ('emotion', )
  seed: 123
