experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
       - dataloader: AudioAttribute
         audio_features: ../dataset/{0}/audio_embeddings/maest
  dataset: onion
  top_k: 50
  evaluation:
    cutoffs: [ 10 ]
    simple_metrics: [ Precision, nDCG, HR ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.SiBraR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: nDCG@10
        restore: False
      lr: [ 0.001 ]
      num_neg: [ 16 ]

      input_dim: 256
      item_modalities: ('audio', )
      epochs: 2
      factors: 64
      weight_decay: 1e-3
      normalize_single_branch_input: True
      use_user_profile: True
      cl_weight: 1e-7
      batch_size: 256
      l_w: [ 1e-2 ]
      loaders: ('AudioAttribute', )
      seed: 123