experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/emotion_embeddings/autotag_profiles
  dataset: onion
  top_k: 50
  evaluation:
    cutoffs: [ 10 ]
    simple_metrics: [ Precision, nDCG, HR ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.SiBraR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: nDCG@10
        restore: False
      lr: [ 0.001, 0.0001]
      input_dim: 256
      item_modalities: ('visual', )
      epochs: 200
      factors: 64
      cl_weight: 0.
      batch_size: 1024
      l_w: [ 1e-5, 1e-2 ]
      loaders: ('VisualAttribute', )
      seed: 123