experiment:
  backend: pytorch
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/interactions.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/visual_embeddings/resnet
        #visual_features: ../data/{0}/emotion_embeddings/gems
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/textual_embeddings/bert
      - dataloader: AudioAttribute
        audio_features: ../data/{0}/audio_embeddings/musicnn
      - dataloader: EmotionAttribute
        emotion_features: ../data/{0}/emotion_embeddings/gems
  dataset: sample
  prefiltering:
    strategy: iterative_k_core
    core: 5
  splitting:
    save_on_disk: True
    save_folder: ../data/sample/splits
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
    validation_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
  top_k: 50
  evaluation:
    cutoffs: [ 10, 20, 50 ]
    simple_metrics: [ Recall, Precision, nDCG, HR ]
    paired_ttest: False
    wilcoxon_test: False
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    ItemKNN:
        meta:
          save_recs: False
        neighbors: 40
        similarity: cosine
        implementation: aiolli
    BPRMF:
      meta:
        save_recs: False
      epochs: 10
      factors: 10
      lr: 0.001
      bias_regularization: 0
      user_regularization: 0.0025
      positive_item_regularization: 0.0025
      negative_item_regularization: 0.0025
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True
    LightGCN:
      meta:
        save_weights: False
        save_recs: False
        verbose: False
      lr: 0.0005
      epochs: 50
      batch_size: 512
      factors: 64
      l_w: 0.1
      n_layers: 1
      n_fold: 5
    external.BM3:
      meta:
        save_weights: False
        save_recs: False
        verbose: False
      lr: 0.01
      multimod_factors: 64
      reg_weight: 0.01
      cl_weight: 2.0
      dropout: 0.3
      n_layers: 2
      modalities: ('visual', 'textual')
      loaders: ('VisualAttribute', 'TextualAttribute')
      epochs: 200
      factors: 64
      lr_sched: (1.0,50)
      batch_size: 1024
      seed: 123