experiment:
  backend: pytorch
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/interactions.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/visual_embeddings/resnet
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/textual_embeddings/bert
      - dataloader: AudioAttribute
        audio_features: ../data/{0}/audio_embeddings/musicnn
      - dataloader: EmotionAttribute
        emotion_features: ../data/{0}/emotion_embeddings/gems
  dataset: sample
  prefiltering:
    strategy: iterative_k_core
    core: 5
  splitting:
    save_on_disk: True
    save_folder: ../data/sample/splits
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
    validation_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
  top_k: 20
  evaluation:
    cutoffs: [ 1, 5, 10, 20]
    simple_metrics: [ Recall, Precision, nDCG, HR, EFD, EPC, ARP, PopREO, PopRSP ]
    paired_ttest: False
    wilcoxon_test: False
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    ItemKNN:
          meta:
            save_recs: False
          neighbors: 40
          similarity: cosine
          implementation: aiolli
    external.BM3:
      meta:
        save_weights: False
        save_recs: False
        verbose: False
        validation_rate: 1
        validation_metric: nDCG@10
      lr: 0.01
      multimod_factors: 64
      reg_weight: 0.01
      cl_weight: 2.0
      dropout: 0.3
      n_layers: 2
      modalities: ('visual', 'textual', 'audio', 'emotion')
      loaders: ('VisualAttribute', 'TextualAttribute', 'AudioAttribute', 'EmotionAttribute')
      epochs: 200
      factors: 64
      lr_sched: (1.0,50)
      batch_size: 1024
      seed: 123