experiment:
  backend: pytorch
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/onion_elliot_binarized.tsv
  splitting:
    save_on_disk: True
    save_folder: ../data/{0}_splits/
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
    validation_splitting:
      strategy: random_subsampling
      test_ratio: 0.1
  dataset: onion
  top_k: 20
  evaluation:
    cutoffs: [ 10, 20 ]
    simple_metrics: [ Recall, nDCG ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    MostPop:
      meta:
        verbose: True
        save_recs: True
    external.BPRMF:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: NDCG@10
        restore: False
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      epochs: 200
      factors: 64
      batch_size: 1024
      l_w: [ 1e-5, 1e-2 ]
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: NDCG@10
        verbose: True
