experiment:
  data_config:
    dataset_path: ../dataset/{0}/interactions.tsv
    side_information:
    - dataloader: EmotionCategoricalAttributes
      emotion_categorical_features: ../dataset/{0}/emotion_embeddings/gems
    - dataloader: EmotionAttribute
      emotion_features: ../dataset/{0}/emotion_embeddings/gems
    strategy: dataset
  dataset: emma
  evaluation:
    cutoffs:
    - 1
    - 5
    - 10
    - 20
    paired_ttest: false
    simple_metrics:
    - Recall
    - Precision
    - nDCG
    - MRR
    - HR
    - EFD
    - EPC
    - ARP
    - PopREO
    - PopRSP
    - ItemCoverage
    - UserCoverage
    wilcoxon_test: false
  external_models_path: ../external/models/__init__.py
  gpu: 0
  models:
    MultiVAE:
      batch_size:
      - 128
      - 256
      - 512
      dropout_pkeep: 1
      early_stopping: &id001
        monitor: nDCG@10
        patience: 5
        verbose: false
      epochs: 200
      factors: 64
      factors_multimod: 64
      intermediate_dim:
      - 300
      - 400
      - 500
      latent_dim:
      - 100
      - 200
      - 300
      loaders: ('EmotionAttribute', )
      lr:
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
      meta: &id002
        hyper_opt_alg: grid
        restore: false
        save_recs: false
        save_weights: false
        validation_metric: nDCG@10
        validation_rate: 1
        verbose: false
      modalities: ('emotion', )
      reg_lambda:
      - 0.1
      - 0.0
      - 10
      seed: 123
  prefiltering:
    core: 5
    strategy: iterative_k_core
  splitting:
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
    validation_splitting:
      strategy: random_subsampling
      test_ratio: 0.1
  top_k: 20
model_defaults:
  batch_size: 512
  early_stopping: *id001
  epochs: 200
  factors: 64
  factors_multimod: 64
  loaders: ('EmotionAttribute', )
  meta: *id002
  modalities: ('emotion', )
  seed: 123
