experiment:
  backend: pytorch
  models:
    external.LATTICE:
      batch_size: 1024
      lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
      l_w: [1e-5, 1e-2]
      n_layers: 1
      n_ui_layers: 2
      top_k: 20
      l_m: 0.7
      factors_multimod: 64
