experiment:
  backend: pytorch
  models:
    external.CLCRec:
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      batch_size: [512, 1024]
      multimod_factors: 64
      reg_weight: [ 0.1, 0.01, 0.001 ]
      lr_lambda: [ 0.1, 0.5, 0.9 ]
      num_sample: 0.5
      num_neg: [32, 64, 128]
      temperature: [0.1, 0.5, 1.0]